---
version: '1.0'
box: abs

name: semver

# pipeline -> stage -> tasks

stages:
  - name: pkg
    tasks:
      - task.id: customtask
        type: cmdline
        workdir: ${ws.dir}
        command: ./pkg.sh
  - name: artifact
    tasks:
      - task.id: ftpartifact
        scm.type: git
        artifact.lane: jenkins
        fileset.dir: ${ws.dir}
        fileset.includes: ${meta.name}-*.tar.gz

pipelines:
  - name: dev
    stages:
      - pkg
      - artifact

default: dev
